version: '3.3'

services:
  cli:
    image: yehuda/wordpress:cli-php${PHP_VER:-7.1}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - db
    networks:
      - database
    restart: always
  web:
    image: nginx:alpine
    volumes:
      - wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - wordpress
    networks:
      - web
    restart: always
  wordpress:
    image: yehuda/wordpress:php${PHP_VER:-7.1}-fpm-alpine
    volumes:
      - wordpress:/var/www/html
    env_file:
      - wordpress.env
    depends_on:
      - db
    networks:
      - database
      - web
    restart: always
  db:
    image: mariadb:${MARIADB_VER:-10.2}
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - mariadb.env
    networks:
      - database
    restart: always

volumes:
  wordpress:
  db-data:

networks:
  database:
  web:
