version: '3.3'

services:
  cli:
    image: wordpress:cli-php7.1
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - db
    networks:
      - database
  web:
    image: nginx:alpine
    volumes:
      - wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    networks:
      - web
  wordpress:
    image: wordpress:php7.1-fpm-alpine
    volumes:
      - wordpress:/var/www/html
    env_file:
      - wordpress.env
    depends_on:
      - db
    networks:
      - database
      - web
  db:
    image: mariadb:10.2
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - mariadb.env
    networks:
      - database

volumes:
  wordpress:
  db-data:

networks:
  database:
  web:
