version: '3'

services:
  web:
    image: yehuda/wp-nginx:latest
    volumes:
      - wordpress:/var/www/html
    ports:
      - "127.0.0.1:${WEB_PORT}:80"
      - "127.0.0.1:${WEB_STATIC_PORT}:8080"
    depends_on:
      - wordpress
    networks:
      - web
    restart: unless-stopped
  wordpress:
    image: yehuda/wordpress:php${PHP_VER:-7.3}-fpm-alpine
    volumes:
      - wordpress:/var/www/html
    env_file:
      - wordpress.env
    depends_on:
      - db
    networks:
      - database
      - web
    restart: unless-stopped
  db:
    image: mariadb:${MARIADB_VER:-10.2}
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - mariadb.env
    networks:
      - database
    restart: unless-stopped

volumes:
  wordpress:
  db-data:

networks:
  database:
  web:
